### ISSUE TITLE
Dimensional Doors: Reborn Post Alpha Improvements

### ISSUE THREAD

**Issue by ZombieHDGaming** [DimensionalDevelopment/DimDoors#1]
- [x] Add JSONs to load dungeon schematics

- [x] Generating Transient door structures in the world (**Dungeon Overworld Structures**)

- [x] Add Monoliths and teleportation to Limbo

- [x] Add chest-loot

- [x] Fix NPE for personal doors causing ticking block entity

- [x] Rift Remover and Rift Signature implementation? Or something close to that?

- [x] Rift growth

- [x] Mechanics to check if players are allowed entrance to the pocket they have just entered in, and if they aren't flying inbetween pockets.

**Comment by Runemoro** [comment]
Rift growth now works too! We can finally close our oldest issue :)
