### ISSUE TITLE
Opening a Deep Dark Portal in a pocket dimension

### ISSUE THREAD

**Issue by Tr4shM0nk3y** [DimensionalDevelopment/DimDoors#100]
When using a deep dark portal from within a pocket dimension, upon traveling back from the deep dark, you get placed nowhere near a bed, the original spawn point of the world or the door to the pocket dimension. When traveling back to the pocket dimension, the portal is gone and the bug is 100% reproducable.

Latest-log when recreating this "bug"
https://pastebin.com/aqYh9ZwV

For a Skyblock pack like mine, this is a pretty big issue.

**Comment by Robijnvogel** [comment]
Was this, perhaps, a Private Pocket? That could explain half of the issue.

If it's not a Private Pocket, could you go into the Pocket, place down any block, exit the Pocket, re-enter it through the entrance Door and see if the block is still there?

**Comment by Tr4shM0nk3y** [comment]
Alright let me test that as well, I just have been given the info you have so far, gonna take me a bit

**Comment by Tr4shM0nk3y** [comment]
Okay, so from testing: 
The second half of the issue (the block disappearing) seems to only be in a Private Pocket.
When entering the Deep Dark portal from within a Treasure pocket (gold door), returning to the overworld from the deep dark still sends you into nowhere, same with an iron dim door.

**Comment by Robijnvogel** [comment]
Then the block disappearing is a known issue with Personal Pockets that is pretty much at the top of our todo-list. 😉 

1. Okay, so where does it send you back to from the Deep Dark?
2. The exact coordinates would help. Is it always the exact same position?

3. What happens when you enter the Deep Dark from another dimension different from the actual Overworld and then return? For instance, the Nether, the End or another modded dimension like the Twilight Forest or the Moon?

**Comment by Tr4shM0nk3y** [comment]
1. It always sends you back to the overworld
2. They seem to change everytime you travel back from the deep dark
3.
- Entering Deep Dark from the Nether; back to the overworld (x-4058 z-3794, those are the same coords as the coords of the portal in the deep dark)
- from the End; same result as the Nether, you get spit out at the portal coords from the deep dark.
- from "The Erebus"; almost same result, but both x&z coord are 1 less

That's all the dimensions I have in the pack at the moment.

**Comment by Robijnvogel** [comment]
So the only bug here is that the return coordinates seem to be random?

**Comment by Tr4shM0nk3y** [comment]
Well, going into the Deep Dark from the overworld and back works without problem, it seems that using a deep dark portal from within any other dimension breaks it. The return coords in the overworld seem to be the exact same as the coords you leave from in the Deep Dark. I would think now this is a problem with Extra Utils in particular, not with DimDoors. I only know of this issue now because players of my pack seem to experiment with the different dimensions.

**Comment by Tr4shM0nk3y** [comment]
With this in mind, I think we can close this issue :) Thanks for the help anyway :D
