### ISSUE TITLE
Cannot Spawn Entity Crash

### ISSUE THREAD

**Issue by alexis-evelyn** [DimensionalDevelopment/DimDoors#106]
The crash log is https://paste.dimdev.org/abulutacuc.mccrash

To reproduce I walk through a new wood door that I just created. Since I have VanillaFix installed all it does is just notify me of the crash in the top right corner of the screen and I just keep playing as usual, but someone else may have their whole modpack shut down. This doesn't happen everytime, only the times when the doors successfully link and not cause me to have to manually travel back to the original door. There is no crash when the doors don't work.

This appears to be similar to issue #41, except I don't have a corrupted world. The lack of a corrupted world may be a result of VanillaFix preventing the game from shutting down the world. The version is #41 is Dimdoors-3.0.6-b.224. My mod version is DimensionalDoors-3.0.9-287.

I may be able to do further testing of the mod by itself later.

Edit:
The coordinates are for the door I exited from. Both doors are in the overworld. Also, the particles for the exit door were visible.

**Comment by Robijnvogel** [comment]
Meh, seems like a problem in ComputerCraft, which is trying to make a turtle do something when a player entity is spawned (or changes dimensions).
