### ISSUE TITLE
Dimensional Doors not working with Lucraft?

### ISSUE THREAD

**Issue by stowaway8888** [DimensionalDevelopment/DimDoors#115]
[crash-2019-05-14_17.56.49-client.txt](https://github.com/DimensionalDevelopment/DimDoors/files/3180102/crash-2019-05-14_17.56.49-client.txt)

**Comment by stowaway8888** [comment]
To note: I can't remove Dimensional Doors. This is on my friends server and he's using it. I need a way to make Lucraft and Dimensional Doors compatible.

**Comment by ConceptApex** [comment]
Hello, I contacted Lucraft (LucraftCore author) to discuss this issue after experiencing the same. It was a quick fix and an update should roll out in a few days time once Lucas adds further improvements to LucraftCore. :)

**Comment by CreepyCre** [comment]
Going to assume this is fixed, please reopen otherwise.
