### ISSUE TITLE
Eternal Fabric has a strange texture

### ISSUE THREAD

**Issue by cactusbee** [DimensionalDevelopment/DimDoors#129]
looks like some kind of developer test pattern, but i have no idea if this is temporary and intended, or not. 

![javaw_2019-11-09_22-50-30](https://user-images.githubusercontent.com/13895658/68538868-1a7b3700-0349-11ea-9780-6704edfedad7.png)

Eternal Fabric blocks have a strange sort of red-X-on-a-white-background texture. while this makes them quite visible in limbo, it also looks extremely strange and is kind of an eyesore when there are enough of them grouped up. in the attached picture, i placed a few in creative mode, however they do appear in "lakes" in limbo as intended. everything else in the mod appears to have the correct look.

i should mention i'm using a resource pack in the above screenshot, however the same thing happens without it.

**Comment by Robijnvogel** [comment]
It **is** a developer texture. Plans are to swap the block for a non-replacable fluid variant.
