### ISSUE TITLE
Personal dimension not being found after server restart, resulting in a new one being generated

### ISSUE THREAD

**Issue by jtljac** [DimensionalDevelopment/DimDoors#135]
Whole File (could not upload the whole file in pastebin as its too long): [latest.log](https://github.com/DimensionalDevelopment/DimDoors/files/4207268/latest.log)
Specific error in console: https://pastebin.com/g7qZaJHs
this error appears to happen when they enter the door

**Comment by Robijnvogel** [comment]
Duplicate of #85
