### ISSUE TITLE
Dimensional door uncraftable :(

### ISSUE THREAD

**Issue by yves-chevallier** [DimensionalDevelopment/DimDoors#145]
On 1.12.2 with the latest snapshop (DimensionalDoors-1.12.2-3.0.9-306.jar) I get this : 

![image](https://user-images.githubusercontent.com/52489316/82095919-53cd9e80-9700-11ea-8d3e-648c77717194.png)

And I don't know how to craft `item.null.name`. Any idea?

**Comment by Robijnvogel** [comment]
The snapshot is for Cubic Chunks compatibility only.
We are aware that some things regarding assets are broken at the moment,
World thread can not be crafted. It can only be found in Dimensional Dungeon loot chests.

**Comment by RossComputerGuy** [comment]
The version I got from curses is having this problem as well. I lost all of my items in a dimensional door but when I got back, the door was gone and only a rift remains.
