### ISSUE TITLE
dungeon rifts are solid invisible door-sized tiles

### ISSUE THREAD

**Issue by lag42** [DimensionalDevelopment/DimDoors#17]
i see a dungeon arch i think the rift is just on the other side of it so i try to walk through it and hit something solid

**Comment by Robijnvogel** [comment]
We know. This is one of the reasons why we haven't released the mod yet.

**Comment by lag42** [comment]
i figured somewhat that it was known, i just wanted an issue open to keep track of it

**Comment by Runemoro** [comment]
Fixed

**Comment by Robijnvogel** [comment]
What commit @Runemoro ?

**Comment by Runemoro** [comment]
@Robijnvogel The one named "Fix transient doors being solid"...

https://github.com/DimensionalDevelopment/DimDoors/commit/8c575270f3766c94a88a15ca414743a6e0fffb9b#diff-f47273f8087ed0d45c373b66409642d7R35
