### ISSUE TITLE
ticking entity crash on the test server upon escaping limbo by placing eternal fabric and charging into it

### ISSUE THREAD

**Issue by lag42** [DimensionalDevelopment/DimDoors#18]
crash log here:
https://gist.github.com/lag42/c83990a8ff634ffb1bb4d8e6550786d4
it repeats every time i join the test server now

**Comment by ZombieHDGaming** [comment]
Can you confirm this with just DimDoors installed, preferably trying to reproduce this in singleplayer? Currently we have some stuff to fix to work properly on servers, this may also be one of them.

**Comment by Runemoro** [comment]
I'm on my phone right now so I won't be able to do anything for a few hours, but looking at the crash log, there isn't any DimDoors in the stack trace, so it's the server sending something wrong to the client.

Zombie, could you try to reproducing the problem?

**Comment by Runemoro** [comment]
Fixed

**Comment by Robijnvogel** [comment]
@Runemoro could you refer to the commit(s) in which this issue was fixed?

**Comment by Runemoro** [comment]
@Robijnvogel https://github.com/DimensionalDevelopment/DimDoors/commit/9cae32189f8810a3fabfa6cb1cfab4e12745ae68#diff-945b7f8cfb6d9cfe8eeb9a88385cbfd1L59
