### ISSUE TITLE
Mod not appearing in new browser (abandoned message)

### ISSUE THREAD

**Issue by MCXopjesh** [DimensionalDevelopment/DimDoors#182]
The DD mod isn't appearing in the new overwolf mod manager mod downloader, I'm pretty sure it's because the mod has been labeled as "abandoned" for some reason. The exact message is: 
"This project is abandoned and its default file will likely not work with the most recent version of Minecraft. Whether this project is out of date or its author has marked it as abandoned, this project is no longer maintained." 
I'm not sure how, but I think you need to apply to get the mod reinstated, its that way for some other mods as well, like millenaire.

**Comment by Oct0bass** [comment]
Transition to Overwolf broke a lot of stuff.  I'm not sure it's possible for the devs to do anything rn, you might just have ot wait until Overwolf fixes stuff.

**Comment by Waterpicker** [comment]
This has been fixed.
