### ISSUE TITLE
LGPL License Incompatibility

### ISSUE THREAD

**Issue by MoleMad** [DimensionalDevelopment/DimDoors#195]
It says the original project you forked is licensed under LGPL, but Github lists this as licensed under MIT? If this was by mistake you should change it immediately to not mislead people into thinking this project is under a permissive license.

**Comment by ZombieHDGaming** [comment]
This is not in fact a mistake, the original mod author gave us permission to relicense the mod to MIT to be more permissive for the future. Just to clarify, I mean StevenRS11, not CannibalVox.
