### ISSUE TITLE
Game crashes when opening singleplayer world

### ISSUE THREAD

**Issue by Orangenal-name** [DimensionalDevelopment/DimDoors#198]
When I open a singleplayer world with this mod, I get the following error:

```
The game crashed whilst mouseclicked event handler
Error: java.lang.NoClassDefFoundError: com/sk89q/worldedit/session/SessionOwner
Exit Code: -1
```

I thought this might mean I need worldedit, so I downloaded the latest version, but now it's just a different error:

```
The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchMethodError: net.minecraft.class_5455.method_30530(Lnet/minecraft/class_5321;)Lnet/minecraft/class_2385;
Exit Code: -1
```

**Comment by Luminiferous348** [comment]
Did you used the stable release from curseforge? Or the experimental 21w10a release from worldedits build site (thats the only worldedit release in existance, that works with dimdoors 21w11a)?

https://builds.enginehub.org/job/worldedit/17499

and no, as far as I know this solution is written nowhere.. I had to do some digging until I found it.

**Comment by ryderbr** [comment]
> Did you used the stable release from curseforge? Or the experimental 21w10a release from worldedits build site (thats the only worldedit release in existance, that works with dimdoors 21w11a)?
> 
> https://builds.enginehub.org/job/worldedit/17499
> 
> and no, as far as I know this solution is written nowhere.. I had to do some digging until I found it.

do you have any links to this? the new version for 21w15a makes the 2nd error as seen earlier.

**Comment by Luminiferous348** [comment]
Ah fantastic.. the link I send was the direct link to the 21w10a version.. but it seems like the world edit devs removed that build.. when I posted the link it was still working. Now I can't find the version on their build site anymore.

I techically still have the jar file, but I don't think, that I am allowed to post the file here. So unless an admin (ie. an DimDoors or WorldEdit dev) tells me its fine, I won't post it.

**Comment by CreepyCre** [comment]
Closed since this was caused by an accidental World Edit dependency that has since been fixed.
