### ISSUE TITLE
Crash after entering a golden dimensional door with a quarzt dimensional door placed first.

### ISSUE THREAD

**Issue by Waterpicker** [DimensionalDevelopment/DimDoors#2]
I entered a golden dimdoor in overworld. Here is log.

https://pastebin.com/AHaPMYTt

**Comment by Robijnvogel** [comment]
The Golden DimDoor has nowhere to lead to.
This is basically caused by the Dungeon Pockets and Transient Door structures not being implemented yet.
After that is done, this should not happen anymore.

**Comment by Waterpicker** [comment]
Ah. Well gonna close this issue then.

**Comment by Waterpicker** [comment]
Reopening because issue technically not fixed.

**Comment by Robijnvogel** [comment]
Solved by enabling the first Dungeons and some resulting issues.
https://github.com/DimensionalDevelopment/DimDoors/commit/0c43bb51f58cba2af6ca509cbcf734eea25998d8
