### ISSUE TITLE
Crash with RFTools Dimensions

### ISSUE THREAD

**Issue by Zsashas** [DimensionalDevelopment/DimDoors#20]
https://github.com/McJty/RFToolsDimensions/issues/181

**Comment by Runemoro** [comment]
Can you test with the latest build? https://github.com/DimensionalDevelopment/DimDoors/releases/tag/untagged-b6070f4a717494e41129

**Comment by Zsashas** [comment]
Got to the main menu successfully.

**Comment by josephcsible** [comment]
Any chance you could do a release soon? People keep running into this.

**Comment by ZombieHDGaming** [comment]
@josephcsible We plan on doing a new release soon, we are just doing some testing since we did a lot of code updates. It should hopefully be out within the next few days hopefully.

**Comment by P3rf3ctXZer0** [comment]
Sweet
