### ISSUE TITLE
Incompatibility with HTM 1.1.2

### ISSUE THREAD

**Issue by CreepyCre** [DimensionalDevelopment/DimDoors#208]
ExplosionMixin needs to be changed to an Inject instead of an Overwrite.
See here for original issue report:
https://github.com/DimensionalDevelopment/DimDoors/issues/205#issuecomment-862915676

**Comment by CreepyCre** [comment]
Should be fixed by e60e20bbd9b945d3ae6015494ebb7e12e0142738.

**Comment by micahflack** [comment]
Appears to have been resolved - thanks!
