### ISSUE TITLE
Ticking Tile Entity: Chicken AI pathing

### ISSUE THREAD

**Issue by kragnoth** [DimensionalDevelopment/DimDoors#21]
Got this after finding what should have held a dimensional door in creative (most likely didn't finish loading, and the client was still rendering the world, but I wasn't getting updates for about 10 seconds)

crash: https://pastebin.com/Nf0zhueg

Do animals get teleported by open dimensional tears?  Maybe it lost its pathing when it teleported, or was trying to path through a door that it didn't know was there?  All I know is I was flying along, come upon something that looked familiar from 1.5.4 days structure wise, and crashed due to a chicken going loco.

**Comment by Robijnvogel** [comment]
@Runemoro 
```
MC 1.12: net/minecraft/pathfinding/WalkNodeProcessor.getSafePoint
Name: a => func_186332_a => getSafePoint
Comment: Returns a point that the entity can safely move to
Side: BOTH
AT: public net.minecraft.pathfinding.WalkNodeProcessor func_186332_a(IIIIDLnet/minecraft/util/EnumFacing;)Lnet/minecraft/pathfinding/PathPoint; # getSafePoint
```

Maybe we should reset the pathfinding of any entity being teleported?
Maybe we should just not allow Entitities to teleport yet? Temporarily, I mean.

**Comment by Runemoro** [comment]
Out of over 1000 chicken I dropped into a DimDoor, I wasn't able to reproduce the bug. If the bug is in fact caused by DimDoors, then it's very rare.

**Comment by Robijnvogel** [comment]
@kragnoth I see you have a lot of other mods. Could you try to reproduce this with as few other mods as possible?

I mean, please try to find the smallest set of other mods with which you **can** reproduce this crash.

@Runemoro have you tried letting the Chickens walk through the portal by themselves?

**Comment by Runemoro** [comment]
Yes, I have. My Minecraft has been open for around 15 minutes now, with chicken walking in and out of DimDoors.

**Comment by kragnoth** [comment]
I'll clone pack and try to narrow down combination.

**Comment by kragnoth** [comment]
I've got it reduced down quite a bit, found the coordinates of a broken chicken.  Removing the mod and I don't crash.  So I'm not sure what the combination of mods is.

**Comment by Robijnvogel** [comment]
Or do as RuneMoro did and **make** chickens pathfind their way through a portal.

**Comment by Runemoro** [comment]
Does it happen with only DimDoors? Are you saying that every time you teleport to that place you crash? If yes, then can you send us your world folder?

**Comment by Robijnvogel** [comment]
@kragnoth
I just randomly stumbled across [this issue](https://minecraft.curseforge.com/projects/modern-skyblock-2/issues/620).
It is very similar to yours, except with a Zombie and they do not have Dimensional Doors installed, from the looks of it.

So can you with positive certainty say that this was DimDoors' fault at all?
Can you reproduce the crash?

**Comment by kragnoth** [comment]
I made a clone of the pack and started a new world after removing any mod that added worldgen and was getting the same crash, so yes, it is reproduceable.  But only if I'm flying around looking for the dimensional doors, so maybe its an issue with pathing and portal placement during chunk generation.

**Comment by Robijnvogel** [comment]
> I should mention there is no door present.
It isn't rendered. We know about this. :)

@kragnoth could you share with us a `.zip` archive containing the contents of your `mods` and `config` folder, so we can try to reproduce this ourselves?

**Comment by kragnoth** [comment]
Its literally just twitch client -> create new modpack, install JEI, Journeymap, latest forge (2586), and drop the dimdoors.jar file from an earlier bug report.  https://github.com/DimensionalDevelopment/DimDoors/issues/20

I then plopped a bunch of chicken eggs around, placed one where the door wasn't rendering, and BAM crash.  I'll see if I can't zip it up once I get done work and errands tonight in about 8 hours.

**Comment by Robijnvogel** [comment]
We try to consistently build the mod against the latest version of Forge.
@Runemoro would know what Forge version our test server uses.

**Comment by Runemoro** [comment]
2555

**Comment by crysyn** [comment]
I am from the other thread... and I just MCEdited my world... There was a chicken there as well.. Could this be an issue with the Baby Zombies riding chickens as opposed to the chicken or a zombie? IIRC the spawn eggs do have a chance to be baby zombies riding the chickens. (Might be wrong on that front but felt it worth mentioning.. Id like this bug fixed regardless of where it is :))

**Comment by crysyn** [comment]
Ok, Honestly thinking this is a bad version of forge.. I have pushed my version to the latest (was on 2566 I believe before) with the pack I am playing where I saw this crash before and so far (3 zombies) no crash has happened. Will update after I actually go play a bit more to make sure its not a fluke.

**Comment by crysyn** [comment]
Still crashes.. I give up.. Good luck.

**Comment by Robijnvogel** [comment]
@Corail31 thinks that https://github.com/MinecraftForge/MinecraftForge/pull/4602 might offer a solution to this issue.

**Comment by crysyn** [comment]
Anyone have a pinpoint on the version of forge that introduced this? id be ok with just rolling back until I can go forward again :)

**Comment by crysyn** [comment]
ok so I didnt give up.. reverting back to version 2.7.3.2 of the mod pack and version .2560 of Forge seemes to have cleared this up. One or the Other did not do it, there is some weird combination going on here.. But since there are 226 mods in the pack .. I am drawing the line of testing each mod out to see where the bad egg is.. I will note that I got this crash to happen with the PlayerSkin thing, the Ember Golems and Zombies through out my testing.. So it was not limited to Only the zombie.

**Comment by 4karion** [comment]
I'm having the same problem with literally only dimdoors-3.0.0-beta-4 installed. Tested with forge .2586 & .2587
The doors are not spawning at all, only the two pillars and the floor. And if you spawn any animal there, as soon as they try to move, the game crashes.

**Comment by Robijnvogel** [comment]
We already have an idea what the problem may be. Forge added something for Entity pathfinding for modded blocks. If so, vanilla Doors would have had the same problem if it weren't for the fact that they aren't modded.

**Comment by crysyn** [comment]
Would this also be an issue for trap doors? Those are the only 'door' type things I have in my mob farm.

**Comment by Robijnvogel** [comment]
I believe this is only a problem for Transient Doors at the moment and I've just identified the fault in-code:
https://github.com/DimensionalDevelopment/DimDoors/blob/1.12-WIP/src/main/java/org/dimdev/dimdoors/shared/blocks/BlockDimensionalDoorTransient.java#L37

**Comment by Runemoro** [comment]
I set the bounding box to null to disable collisions with the door.
