### ISSUE TITLE
[Fabric 1.17] Incompatible with Simply Improved Terrain

### ISSUE THREAD

**Issue by jakeismyname** [DimensionalDevelopment/DimDoors#210]
Crashes on start, tested on latest fabric loader, with builds of both mods from the latest commits.

Log: https://hastebin.com/mipufevegi.kotlin

Not 100% sure if this is DimDoors' fault, so if it isn't please tell me and I will go create an issue over there.

**Comment by CreepyCre** [comment]
Seems to be caused by Simply Improved Terrain. From checking Curseforge it seems there is no 1.17 release of Simply Improved Terrain and their 1.17 branch is actually built against 21w19a. You'll likely just have to be patient for them to update to 1.17.

**Comment by jakeismyname** [comment]
Alright, thank you!
