### ISSUE TITLE
Walking through portal does nothing

### ISSUE THREAD

**Issue by PikachuPlaysSKY** [DimensionalDevelopment/DimDoors#212]
Walking through portal does nothing sometimes. I am stuck in a portal now and every door just do nothing when i walk through

**Comment by PikachuPlaysSKY** [comment]
Registry 'dimdoors:virtual_type' was empty after loading

getting this from game output. this might be something??

**Comment by Dusty-Sprinkles** [comment]
try falling into the door from above, if it works similar issue to #204

**Comment by CreepyCre** [comment]
Fixed by 21d1337b8f7bf3c39eaab2ea2b38029e7bc36412

**Comment by PikachuPlaysSKY** [comment]
how do i put that into the mod or will you be releasing an update soon?
