### ISSUE TITLE
[1.17] Dimdoors causing certain structures not to generate

### ISSUE THREAD

**Issue by cybercat5555** [DimensionalDevelopment/DimDoors#214]
Fabric 0.11.6
Fapi 0.36.0
Dimdoors DimensionalDoors-4.0.0beta.2-11.06.2021

Dimdoors causes certain structures, such as Villages and Strongholds, not to generate. Commands and Eyes of Ender point to them, but nothing exists there. When Dimdoors is removed and the same coords are gone to, the structures generate.  However other structures, such as Ruined Portals, Desert Pyramids, and Dimdoor's own Rift Shrines do generate.

**Comment by CreepyCre** [comment]
Already fixed by 643f1925e7d44922217f11d6a73ca6aafeed3989, you'll have to wait for the next beta release. (Alternatively compile from the latest committ yourself)
