### ISSUE TITLE
1.17 Server Crashes with 1.17 DimDoors installed.

### ISSUE THREAD

**Issue by Betterclusm** [DimensionalDevelopment/DimDoors#220]
I actually do not know the reason why does the server crash but after i installed dim door it worked fine in singleplayer but in my server when i start the server it crashes.

**Comment by CreepyCre** [comment]
Duplicate of #213, this is already fixed in dev.
You can either wait for a new release, compile from the latest commit yourself or ask someone in our Discord to do it for you.
