### ISSUE TITLE
ConfiguredFeature was found to be not registered.

### ISSUE THREAD

**Issue by schuberty** [DimensionalDevelopment/DimDoors#223]
I used Blame to find out what was the issue with my world not generating some stuff.

The [latest.log](https://github.com/DimensionalDevelopment/DimDoors/files/6833645/latest.log) showed that there is some unregistered stuff.

**Comment by BoogieMonster1O1** [comment]
Fixed in db3a98f6
I'll push a fix to curseforge later today
