### ISSUE TITLE
World corruption

### ISSUE THREAD

**Issue by dusoad** [DimensionalDevelopment/DimDoors#228]
Most of the time using an iron door inside wooden dimensional door or a natural rifft will not teleport to a new dimension immeadiately and just tell me "Something went wrong trying to teleport you, please report this bug" (error from that: https://pastebin.com/sJXnT8zT), if this happens the world will not be able to be loaded again from the menu no matter what I try (error loading world: https://pastebin.com/9JqRcSne). If i stay in the door it will teleport after a bit.

Using a self built version cloned yesterday in Minecraft 1.17.1, same issue with newest version from curseforge.

**Comment by dusoad** [comment]
Seems to be my setup somehow, dunno why only dimensional doors has this issue but I can't reproduce it on other machines.

**Comment by CreepyCre** [comment]
Feel free to dm me on Discord if you want someone from the dev team to have a closer look at your case.
CreepyCre#8303
If it happens to you there is always a chance it can happen to other people.

**Comment by CreepyCre** [comment]
There is also a chance b604e71be53d89608306395d80cc9decefa85310 fixes it. If it doesn't I still have an idea what could cause this otherwise.
#227 is likely the same issue.
