### ISSUE TITLE
Limbo lagging and crashing upon exit

### ISSUE THREAD

**Issue by Shoes4Clues** [DimensionalDevelopment/DimDoors#231]
While inside limbo, there is severe lag that builds up over time and if it's too bad, the game crashes entirely. When exiting at all, the game always crashes if it's at all loaded. The only way to safely exit is via /kill.

**Comment by Waterpicker** [comment]
Do you have any more details? What mods were running with it, which version of the mod, et ect.

**Comment by CreepyCre** [comment]
Closed due to inactivity. Feel free to reopen.
