### ISSUE TITLE
[1.17.1] PocketDirectory writeNbt ArrayIndexOutOfBoundsException crash.

### ISSUE THREAD

**Issue by TheGrimsey** [DimensionalDevelopment/DimDoors#234]
Happened a few minutes after leaving a public pocket on a server.

- DimDoors 4.0.0+beta.2-26.07.2021
- Fabric API 0.40.0+1.17

**Crash report:**
> java.util.concurrent.CompletionException: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 17

[crash-2021-09-06_19.29.01-server.txt](https://github.com/DimensionalDevelopment/DimDoors/files/7117658/crash-2021-09-06_19.29.01-server.txt)

**Line throwing error in code:**
https://github.com/DimensionalDevelopment/DimDoors/blob/1.17/src/main/java/org/dimdev/dimdoors/world/pocket/PocketDirectory.java#L79

**Comment by CreepyCre** [comment]
Pushed something that likely fixes this, just reopen this issue should you experience this crash again. (provided you've switched to an updated version by then)
