### ISSUE TITLE
Rifts...

### ISSUE THREAD

**Issue by edgaradr223** [DimensionalDevelopment/DimDoors#239]
Trying to find a way to completely disable rifts as what we (me and my players) like from the mod is the dimension and exploration mechanics added by this incredible mod, nobody wants to remove rifts as this adds nothing to the game, not even rewarding and only make people and gamemasters to lose time cleaning away to remove lag and everybody get frustrated, is there for god´s sake a way to completely remove them and let only the doors spawning and the void mechanics? any help would be appreciated.

Thank you in advance.

(using 1.12.2 version for forge)

**Comment by edgaradr223** [comment]
unfortunately i had to remove the mod from my modpack T_T i really loved it, waiting for new versions if possible, may be extraordinary to add your mod again

**Comment by CreepyCre** [comment]
Keeping this open as a feature request.

**Comment by Myridium** [comment]
What is the problem with the rifts exactly? What if you could turn off rift spreading, or set a timeout before they disappear? And what if the issues with lag were resolved through optimisation? I think that would resolve your issues without unduly disrupting the way the mod functions.

**Comment by edgaradr223** [comment]
> What is the problem with the rifts exactly? What if you could turn off rift spreading, or set a timeout before they disappear? And what if the issues with lag were resolved through optimisation? I think that would resolve your issues without unduly disrupting the way the mod functions.

it may be viable for some modpackers using small-medium modpacks, or people playing with their friends on a small server, but when your modpack has over 300 mods + over 60 plugins and over 350 people playing at the same time 24/7 it becomes an issue, believe me, in my case; me and my players  love what the mod has to offer in terms of exploration and utility but its odd to deal with the lag generated by rifts, even with optimization it wont help on large modpacks because as i said; there are too many players and particles are sort of the laggest resources in minecraft, now imagine that the mod receives an optimization update to reduce the particles to minimal by default or set them up for a certain period of time but still 160 out of 300 players decide to open a dim door at the same time... its going to break things and thats why a lot of modpackers (friends with large and recognized servers) made up the same decision as me to surrender and remove the mod bcs of the same reason; we have years and years spent on this and it has always been a problem,  if you dont believe me make your own research by typing dimensional doors mod rifts issue on google, you will see a lot of people complaining, so its not a solution for me, it would be a solution for a lot of modpackers and i can assure that it will have a powerful and  positive impact on mod downloads if its done, i will be the first one telling my players (2000+ whole university) to download the mod again from curseforge and i know a lot of modpackers will... (im not saying its an easy task) it will depend on how the mod was written and only the mod owner will know if its possible and if he is willing to do this, he will have the last word on this.

**Comment by Myridium** [comment]
Particle effects are graphical effects rendered on the client side; servers would not be affected by that.

If there is lag generated by the rifts, then this mod is not well-optimised. The solution is optimisation.

I do think an option should be added to prevent growth of rifts, in case the gameplay implications are annoying to some players.

**Comment by edgaradr223** [comment]
> Particle effects are graphical effects rendered on the client side; servers would not be affected by that.
> 
> If there is lag generated by the rifts, then this mod is not well-optimised. The solution is optimisation.
> 
> I do think an option should be added to prevent growth of rifts, in case the gameplay implications are annoying to some players.

It doesnt matter if particles are rendered client or server side dude, players are moving all around the workd opening and crossing dimensions and portals anytime, the way rifts grow is just crazy and affects every player that is 2-4 chunks away and at the same time rifts grow because of the presence of these players, it affects server since gamemasters have to login anytime to try and remove VERY LARGE rift clusters, taking 1-3 hours sometimes isnt that crazy? Where is the fun on this? That time would have been spent exploring a dungeon, fighting pvp battles with a friend or just killing creatures to gain experience... having a large modpack with this mod and lot of players is frustrating for everyone and being objective rifts add 0 real-rewarding playable -fun content to the game no players are interested in cleaning rifts they just want to explore so whats the point on keeping them? (considering people who plays rpg-dungeons crawl or hack n slash servers are always looking for dungeons, mysteries and pvp) as an example; its like travelling to the sea to just clean up petroleum oil from shells and rocks, i mean, there is a large community interested in that activity but there is also a large community who wants to travel to the sea just to have fun and there is nothing wrong about that... That being said rifts are like the rocks and shells, except that rifts make any activity impossible (even clean shells and rocks LOLl), thats why having an option to disable or enable rifts is necessary for those modpackers running in issues with the mod, you can always open a ticket like i did to ask for something that is more functional to you and your players (if any), who knows? Maybe both options can be added, or maybe none can be added.

**Comment by Myridium** [comment]
Again, all your problems are solved by adding a toggle for rift growth, and optimising the mod so that rifts do not cause lag.

Rifts serve as a way to return to a dimension. It protects players from accidentally destroying a ton of their progress in a pocket dimension when they accidentally break the entrance portal. It is easy to clean up rifts.

Like the ocean, petroleum and plastic, the real solution comes from getting people to clean up after themselves to begin with. If the server is lagging so much because of the portals, I'm sure your players will be happy to clean up their mess.

You could also rent a more powerful server that can meet the needs of your players.

**Comment by CreepyCre** [comment]
I would like to note that as of now updates to the 1.12.2 version of Dimensional Doors are rather unlikely. There are larger reworks planned for the current 1.17.1 version and even after those are done it is very questionable if anyone would be willing to backport any changes. Most of the team is rather busy, so we simply don't have the time for it. If you want to make specific changes for your server there is always the option of forking the project.

**Comment by Waterpicker** [comment]
I would also add if you take up the 1.12.2 iteration. We wouldn't be against posting it on the curseforge. This is why a cubic chunks compat version of the older versions exists.

**Comment by edgaradr223** [comment]
> I would also add if you take up the 1.12.2 iteration. We wouldn't be against posting it on the curseforge. This is why a cubic chunks compat version of the older versions exists.

Thats good to know, im going to ask for a rework to the modder team who made some custom mods/plugins for my server and let you know the results once done, maybe adding some custom config options/rooms/types of doors and some compatibility for magma/mohist servers (which is very unlikely), thanks for your reply and the interest shown by CreepyCre by maintaining this ticket open even when i decided to close it before.

**Comment by TheComputerizer** [comment]
Forgot to close this since there are more config options related to rifts now
