### ISSUE TITLE
Wrong Gecko?

### ISSUE THREAD

**Issue by Sharterra** [DimensionalDevelopment/DimDoors#240]
Dimension Doors for 1.17 for Fabric is trying to use the older version of Geckolib for 1.16 which obviously isn't gonna fly.  Granted Gecko seems to have that issue with a lot of mods on Curseforge over the last few months so it might not even be an issue on yah end as other mods are also going haywire and suddenly relying on the wrong version to.  Is this just a symptom of most mod testing happening on 1.16?

**Comment by CreepyCre** [comment]
Waterpicker is on it rn, lol. Thank you for the report.

**Comment by Waterpicker** [comment]
I referenced the old way geckolib separated fabric/forge before curseforge fixed its stuff. This has been corrected on the new Beta's page.
