### ISSUE TITLE
Freeze and crash after entering limbo

### ISSUE THREAD

**Issue by 533kr** [DimensionalDevelopment/DimDoors#245]
**Crash log:** https://bytebin.lucko.me/lTQu5PBmvO
**Video (initial crash):** https://youtu.be/FkBbMfILNkc
**Video (reloading after initial crash):** https://youtu.be/Dc6MG5cpUmk

The rest of the dimensions seem to work as intended, near as I can tell, but upon first entering limbo I have maybe 1-2 minutes before it inevitably freezes and then crashes. Once it happens once, it'll crash within a few seconds of loading the world every time. I thought it might be an Iris compat issue at first, but at this point I've stripped down everything but the few miscellaneous library/utility .jars and it's still doing the thing.

**Comment by CreepyCre** [comment]
Should be fixed by 464eb7e2b8fcd5005ea909821d417f1b1a2678a8.
