### ISSUE TITLE
Several small visual bugs.

### ISSUE THREAD

**Issue by pyro448** [DimensionalDevelopment/DimDoors#26]
- [x] All door items added by Dimensional Doors are unusually large in the hand and when dropped as items.

- [x] ~~The sky in Limbo is white, and the red eye in the sky is not visible when using the night vision effect.~~

- [x] Transdimensional trapdoors are missing the portal effect.

Mod version: "dimdoors-3.0.0-beta-4" which is currently installed on the test server.

**Comment by Runemoro** [comment]
The limbo sky isn't white for me and the sun renders correctly. Does this happen when you run only DimDoors and no other mods?

**Comment by pyro448** [comment]
I removed all mods except for Dim Doors, and the sky appeared normal. However, the first observation was done on the test server, while this second observation was in singleplayer.

I also noticed that dying inside a pocket dimension does not send you to limbo. I ended up using the teleporter item from Custom NPCs to teleport to limbo, and then removed Custom NPCs once I was there.

**Comment by Runemoro** [comment]
Dying in a pocket dimension should not send you to limbo. Only dying in the dungeon pocket dimension should. Does it still happen on the test server with only DimDoors and Biomes O Plenty?

**Comment by pyro448** [comment]
The dungeon pocket dimension sent me to limbo upon death as expected. The sky in limbo appears normal. However, I now remember I had the night vision effect active when I was there last time. Upon applying the effect, the sky became white.

**Comment by Runemoro** [comment]
Night vision bug is vanilla behavior of inverting the fog color. 
```java
        if (entity instanceof EntityLivingBase && ((EntityLivingBase)entity).isPotionActive(MobEffects.NIGHT_VISION))
        {
            float f15 = this.getNightVisionBrightness((EntityLivingBase)entity, partialTicks);
            float f6 = 1.0F / this.fogColorRed;

            if (f6 > 1.0F / this.fogColorGreen)
            {
                f6 = 1.0F / this.fogColorGreen;
            }

            if (f6 > 1.0F / this.fogColorBlue)
            {
                f6 = 1.0F / this.fogColorBlue;
            }

            // Forge: fix MC-4647 and MC-10480
            if (Float.isInfinite(f6)) f6 = Math.nextAfter(f6, 0.0);

            this.fogColorRed = this.fogColorRed * (1.0F - f15) + this.fogColorRed * f6 * f15;
            this.fogColorGreen = this.fogColorGreen * (1.0F - f15) + this.fogColorGreen * f6 * f15;
            this.fogColorBlue = this.fogColorBlue * (1.0F - f15) + this.fogColorBlue * f6 * f15;
        }```

Doesn't happen when the fog is completely black (pocket dimensions) because of how Forge fixes a vanilla division by zero bug:
```            // Forge: fix MC-4647 and MC-10480
            if (Float.isInfinite(f6)) f6 = Math.nextAfter(f6, 0.0);
```

**Comment by Robijnvogel** [comment]
So in short, the __black__ sky being turned bright __white__, is the **intended** implementation  of Vanilla Night Vision.

**Comment by Runemoro** [comment]
Fixed
