### ISSUE TITLE
AFter entering dimension black client

### ISSUE THREAD

**Issue by TheButterbrotMan** [DimensionalDevelopment/DimDoors#268]
https://bytebin.lucko.me/3BnVkBrJnT

**Comment by Waterpicker** [comment]
Are you using 4.0.0 release or the recently pushed 4.0.1 hotfix? I got this error reported in the discord already.

**Comment by TheButterbrotMan** [comment]
4.0.0-1.18.2

**Comment by Waterpicker** [comment]
Yea. Try 4.0.1. 

The crash is caused by me forgetting to fully remove reference to a schematic that was causing crashes during testing. One issue with the dungeon system being datapack driven now. Make one mistake and you get stuff like this happening. Powerful but easy to get wrong.

**Comment by TheButterbrotMan** [comment]
Works! Thank you.

**Comment by Waterpicker** [comment]
It already worked in general. Its just prior to me fully purging references to the troublesome entry. It would crash upon trying to use something that didn't exist. There was a chance of it happening so crash.
