### ISSUE TITLE
Repeating seed glitch

### ISSUE THREAD

**Issue by MatchTerm** [DimensionalDevelopment/DimDoors#269]
Hello,

I am experiencing a weird behavior right now. When DimDoors is installed, the seed of a world will be constant, even between deletion of save files, making the world be the same.

When DimDoors is uninstalled, the repetition is gone as well.

Attached is the log file of booting up the game, creating a world, deleting it, and creating a second one.
[Log.txt](https://github.com/DimensionalDevelopment/DimDoors/files/8378075/Log.txt)

Thank you in advance for the support.

**Comment by Waterpicker** [comment]
You are using Terralith datapack?

**Comment by MatchTerm** [comment]
Is that the one doing it? If so, I apologize, I am very blind

**Comment by Starmute** [comment]
Try removing whichever mod 'agape' is - it might also be causing issues.
