### ISSUE TITLE
[1.18.2 Bug] Gold Doors not working as intended

### ISSUE THREAD

**Issue by itsdinkd** [DimensionalDevelopment/DimDoors#279]
Using a gold door, its supposed to take you to a dungeon, however, in the current latest version, it takes you to a pocket dimension, like an iron door dimension basically. 

I've tested with numerous gold doors in multiple locations and it all takes me to a pocket iron door dimension

![image](https://user-images.githubusercontent.com/35115304/166122063-3c97129c-7205-43b2-9387-15618e678f6e.png)

![image](https://user-images.githubusercontent.com/35115304/166122076-89d78fbb-6adc-45fe-857a-6d2e46b297cc.png)

**Comment by BoogieMonster1O1** [comment]
It's a feature in the 1.18.2 version. You can find dungeons through gateways now

**Comment by itsdinkd** [comment]
How many would one need to go through? I put gold door after gold door in
these new pockets and it kept leading me to the black dimension

**Comment by Waterpicker** [comment]
I think I can explain this. Gold doors were given the ability is a beta feature that was added to test dungeon gen. They were never meant to retain this post release. During my rush to dimdoors properly released, I moved the functionality to a new stone dimdoor that's creative only (item with the dungeon gen stuff on it).

**Comment by Gaming32** [comment]
Could you update the CurseForge page, and close this was wontfix?
