### ISSUE TITLE
Crash while breaking doors

### ISSUE THREAD

**Issue by smithnc07** [DimensionalDevelopment/DimDoors#28]
Version: 3.0.0-beta4 
Forge: 14.23.1.2585

I've been taking a look at the mod and testing out some of the doors. While testing I found that breaking a dim door could result in the client crashing. The logs listed the following error:

> java.lang.ClassCastException: org.dimdev.dimdoors.shared.tileentities.TileEntityEntranceRift cannot be cast to org.dimdev.dimdoors.shared.tileentities.TileEntityFloatingRift
> 	at org.dimdev.dimdoors.shared.blocks.BlockFloatingRift.func_180655_c(BlockFloatingRift.java:82)
> 	at net.minecraft.client.multiplayer.WorldClient.func_184153_a(WorldClient.java:356)
> 	at net.minecraft.client.multiplayer.WorldClient.func_73029_E(WorldClient.java:344)
> 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1892)
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
>

**Comment by Runemoro** [comment]
This was fixed for the next beta, could you try using this: https://github.com/DimensionalDevelopment/DimDoors/releases/tag/untagged-cdef5f1e195e64f8d2d7

**Comment by smithnc07** [comment]
I've been playing around with it for a few minute this morning and have yet to come across the crash. Looks to be addressed. Thank you.
