### ISSUE TITLE
Are dimension doors supposed to drop when the block under is broken?

### ISSUE THREAD

**Issue by Springer-Nocti** [DimensionalDevelopment/DimDoors#283]
Currently running a modpack called AQM2 (Another Quality Modpack 2) and one of my players has been doing as the title says.  I'm just trying to figure out if that's something that's meant to happen given it feels like it shouldn't be.

**Comment by Waterpicker** [comment]
Is this 1.18.2? If so, yes.

**Comment by Springer-Nocti** [comment]
Yeah it is, and thank you!
