### ISSUE TITLE
Game Crash While Attempting to Run Dim Doors 

### ISSUE THREAD

**Issue by BadJju** [DimensionalDevelopment/DimDoors#296]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'dimdoors'!
Exit Code: -1

Edit - 1.17.1

Other mods running at the time include 
![image](https://user-images.githubusercontent.com/109007547/178127977-9d2b3185-a90a-4984-b8d9-2d0279fbc3b3.png)

**Comment by BoogieMonster1O1** [comment]
send the crash report

**Comment by BadJju** [comment]
[crash-2022-07-10_12.36.56-client.txt](https://github.com/DimensionalDevelopment/DimDoors/files/9079439/crash-2022-07-10_12.36.56-client.txt)

**Comment by BoogieMonster1O1** [comment]
Fixed in 1.18+
