### ISSUE TITLE
Players stop rendering after teleport

### ISSUE THREAD

**Issue by MissPotato** [DimensionalDevelopment/DimDoors#30]
**Dimensional Doors Version:** 3.0.0-beta4+125
**Forge Version:" 2587
When passing through the door, players stop rendering. This carries over to the overworld and only logging seems to fix it.

**Comment by Robijnvogel** [comment]
This may not only be the case for players.
I'm testing the dungeon pockets at the moment, and the chests don't seem to render either, until you try to open them, ie. give them an update.

So maybe it's all entities and tile-entity renders.

**Comment by Runemoro** [comment]
I think chests don't render for a different reason. If you generate a pocket while you're already at the pocket's coordinates, none of the blocks render, and you have to reconnect. Chests for some reason sometimes don't render even if you're teleported after the schematic has been fully placed (as it is now), not sure why.

Players render most of the time, but they sometimes stop rendering after they're teleported (maybe something's wrong with the teleport code, though I'm doing it exactly like vanilla does...).

**Comment by Robijnvogel** [comment]
Actually, adding chest loot to the chests, causes an update to the render, so they are not invisible anymore since https://github.com/DimensionalDevelopment/DimDoors/commit/c8c706bac4cbba8c539a22f970e3fc92aeecf94e .

**Comment by Runemoro** [comment]
We should probably still fix this, maybe in the future we'll have a way of marking chests we don't want to be filled with loot.

**Comment by Robijnvogel** [comment]
Also:
https://github.com/DimensionalDevelopment/DimDoors/commit/368565944a882c88846e63c7cffa229808fcac10
