### ISSUE TITLE
rift signatures not working 1.12.2

### ISSUE THREAD

**Issue by zheeeh** [DimensionalDevelopment/DimDoors#301]
rift signatures and stable rift signatures have not been working at all in version 1.12.2 for me (have not tested in other versions). forge version is 14.23.5.2860. someone has already mentioned this in the comments on the curseforge webpage, but im posting it here too. to define "not working" more clearly, the rift signatures seem to do nothing at all. i right click with them, and nothing happens. it moves in my hand as if a right click action has been preformed, but nothing seems to happen. right clicking a second time, or multiple times, does nothing as well. same goes with stabalized warp signatures. right clicking ontop of rifts also does nothing, in case that's how theyre intended to be used. thanks for any help that can be done to fix this

**Comment by Hri7566** [comment]
on my server, when i use the rift signature, i get the error `java.lang.ClassNotFoundException: org.dimdev.ddutils.RotatedLocationNBTWriter`

**Comment by TheComputerizer** [comment]
Yeah dw that was fixed in the recent PR. It should be live on CF in the next few days

**Comment by zheeeh** [comment]
> Yeah dw that was fixed in the recent PR. It should be live on CF in the next few days

thank you!
