### ISSUE TITLE
Teleporting failed with the following exception

### ISSUE THREAD

**Issue by neo0nymous** [DimensionalDevelopment/DimDoors#307]
Hello, i am playing the Fabric modpack "Another Quality Modpack 2 - AQM2 - 1.18.2"

DimDoors Version 4.0.4 - latest

When i tried to walk into a DimDoor in the Overworld this message came in the Console and i didnt get Teleportet. 

Error Code: https://pastebin.com/NjRCdFNf

**Comment by Flashacker-Neo** [comment]
Hi, I have a similar problem with AQM2 in 1.18.2

Version mod : 4.0.4
Here the error code: https://pastebin.com/AR4PyWSK

**Comment by BoogieMonster1O1** [comment]
Fixed in 1.19+
