### ISSUE TITLE
[1.17][CRASH] Crash When Starting Up Dimensional Doors Mod

### ISSUE THREAD

**Issue by eveldun** [DimensionalDevelopment/DimDoors#308]
When The dimension doors mod is opened On The Minecraft Launcher This is the message i get.
`The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'dimdoors'!
Exit Code: -1`

**Comment by BoogieMonster1O1** [comment]
Unsupported version
