### ISSUE TITLE
1.19 broken

### ISSUE THREAD

**Issue by Hallowedz** [DimensionalDevelopment/DimDoors#311]
its calling to something that doesnt exist? https://mclo.gs/8oarJyt link included with the crash report

**Comment by Waterpicker** [comment]
I can explain this. I uploaded the new version at night and uploaded a jar that's useful for developers instead of the main mod so it became the primary file. I attached the actual mod as an extra one. >< I know I need to fix it.

**Comment by zorex73** [comment]
Was this fixed? It doesn't appear so, and I really wanna use this mod.

**Comment by Waterpicker** [comment]
Little hint. You can upload additional files to curseforge. I had the idea of uploading something useful to developers. Being tired. I got the actual mod and this backwards.
