### ISSUE TITLE
[1.19.2 / 5.0.0] Indestructible Quartz Doors in personal pocket dimension aren't bed-proof

### ISSUE THREAD

**Issue by Myrmidontdothat** [DimensionalDevelopment/DimDoors#313]
**Issue**: The quartz door to the exit of a personal pocket dimension can't be broken directly with a pickaxe, but the block it is on can be broken, breaking the door/dropping quartz door item. This can occur via a bed explosion or other means.

Unsure if this is an intended feature or not. Positive feature: Allows player re-locating the door within the pocket dimension. Negative feature: potential loss of door.

**Recreate Error**: Sleep in a bed next to the door of a PPD. Or break Altered Fabric block under it with pickaxe.

**Suggestion**: If unintended, perhaps have the door be placed on an Ancient Altered Fabric block instead.

MC Version 1.19.2 / DimDoors version 5.0.0

**Comment by Myrmidontdothat** [comment]
Door isn't unbreakable. I don't know why I thought that was a thing.

**Comment by Waterpicker** [comment]
Yea. The door is just a dimensional door configured to do the return trip. The rift should still be there. Just plop a door on it and you should be good. The door type doesn't define the type of connection. Well the item version does when you used it but the actual placed down door doesn't.
