### ISSUE TITLE
Dimensional door didnt work when I walked into it

### ISSUE THREAD

**Issue by Agnet75** [DimensionalDevelopment/DimDoors#315]
First time using the modpack "Another Quality Modpack 2" and ran into a Dimensional Door pretty early game, but it wasnt functioning and said to report the error so I copied the error files in the console and pasted it into the following pastebin:

https://pastebin.com/HLKLUiwx

**Comment by Flashacker-Neo** [comment]
Same error on this mod pack in minecraft 1.18.2. But the problem is only on server party and not in my local game.

**Comment by BoogieMonster1O1** [comment]
Fixed in 1.19+
