### ISSUE TITLE
[1.18.2] Server crash (timeout) when entering a DimDoors portal gateway

### ISSUE THREAD

**Issue by Gbergz** [DimensionalDevelopment/DimDoors#317]
Title^

Versions:
DimDoors: 4.0.4 | https://www.curseforge.com/minecraft/mc-mods/dimensionaldoors/files/3732839
Fabric API: 0.59.0
Fabric Loader: 0.14.9

Crash-Report: https://gist.github.com/Gbergz/2d2a983b0adcfbe7d86e9fe568ffc9ec

Max-tick-time is already set to 750000, not default 60000.

**-** Gbergz

**Comment by BoogieMonster1O1** [comment]
I can't seem to be able to reproduce it on the latest version, so I'm assuming we fixed this sometime in the middle.
Probably an erroneous pocket though
