### ISSUE TITLE
Instant death

### ISSUE THREAD

**Issue by ghost** [DimensionalDevelopment/DimDoors#321]
when entering limbo players instantly suffocate in a wall for some reason. what information would be helpful?

**Comment by BoogieMonster1O1** [comment]
Does this happen all the time?

**Comment by ghost** [comment]
yes it happens every time when the reason for entering limbo is falling out of a pocket dimension, if you are killed by another player in the pocket dimension though, you get sent to limbo successfully

**Comment by Sebas-Re** [comment]
> when entering limbo players instantly suffocate in a wall for some reason. what information would be helpful?

Have you set up a worldborder? I've found that doing so leads to players getting instakilled by suffocation, which is very frustrating :/
