### ISSUE TITLE
1.19.3?

### ISSUE THREAD

**Issue by TecEash1** [DimensionalDevelopment/DimDoors#325]
Hi, does anyone know if 1.19.3 is being worked on of if there are any beta builds, if there are great, if not np

**Comment by BoogieMonster1O1** [comment]
The 1.19 branch is fully updated to 1.19.3, but we decided to push more features before releasing

**Comment by TecEash1** [comment]
That's great! Are you able to send the 1.19.3 mod in its current state at the moment?

**Comment by TecEash1** [comment]
> The 1.19 branch is fully updated to 1.19.3, but we decided to push more features before releasing


That's great! Are you able to send the 1.19.3 mod in its current state at the moment?

**Comment by BoogieMonster1O1** [comment]
Updated to 1.19.3 (version 5.1.0)
