### ISSUE TITLE
[Bug]: Crash on startup with Quilt

### ISSUE THREAD

**Issue by MoriyaShiine** [DimensionalDevelopment/DimDoors#330]
### What happened?

Game crashes on startup when using Quilt. Works fine on fabric. class_1813 is MusicDiscItem

### Mod Version

5.1.0-1.19.3

### What versions of Minecraft does this issue happen on?

1.19.3

### Log

```shell
https://gist.github.com/MoriyaShiine/dabf89d20f214a24d3e87260231f0cb8
```

**Comment by BoogieMonster1O1** [comment]
https://github.com/FabricMC/fabric/blob/1.19.3/fabric-transitive-access-wideners-v1/src/main/resources/fabric-transitive-access-wideners-v1.accesswidener#L233
Fabric API adds a transitive access widener for this

https://github.com/QuiltMC/quilted-fabric-api/blob/1.19.3/fabric-transitive-access-wideners-v1/src/main/resources/quilted_fabric_transitive_access_wideners_v1.accesswidener
Quilted Fabric API doesn't yet

**Comment by MoriyaShiine** [comment]
Fixed as of https://github.com/QuiltMC/quilted-fabric-api/commit/b9b7aa333ccb6e2d72e54b4d0498a9fd92a85d5b
