### ISSUE TITLE
Dedicated Serverside Crash 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [DimensionalDevelopment/DimDoors#35]
https://gist.github.com/P3rf3ctXZer0/1f4dd39450bface06fa612a0c98f5eec

Sorry Passing out hopes thos helps.

**Comment by Runemoro** [comment]
This should fix it: https://github.com/DimensionalDevelopment/DimDoors/releases/tag/untagged-206c331af5c629f654d6
