### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by LightFlamr71498** [DimensionalDevelopment/DimDoors#352]
### What happened?

I don't know how to go in editor mode in curseforge

### Mod Version

1.12.2

### What versions of Minecraft does this issue happen on?

1.12.2

**Comment by BoogieMonster1O1** [comment]
what

**Comment by billyp673** [comment]
What does this have to do with DimDoors?

**Comment by TheComputerizer** [comment]
Closing this since it seems irrelevant
