### ISSUE TITLE
[Suggestion]: Use fewer BlockStates

### ISSUE THREAD

**Issue by Lafolie** [DimensionalDevelopment/DimDoors#353]
### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion

### Use the editor below to elaborate.

Hi, I don't use this mod, but I was helping a user on the Fabric discord, when they posted [their logfile](https://mclo.gs/e0BRmYV).

The vast majority of this log is warnings for over 20,000 block states that this mod creates. I just wanted to report this to you, since it is probably something you are unaware of and will definitely want to address.

**Comment by BoogieMonster1O1** [comment]
Fixed in version 5.0.2 (1.19.2)
https://www.curseforge.com/minecraft/mc-mods/dimensionaldoors/files/4328511
