### ISSUE TITLE
[Bug]: Dying in overworld sends you to limbo

### ISSUE THREAD

**Issue by srimpsrimp** [DimensionalDevelopment/DimDoors#360]
### What happened?

I'm not sure if this is an issue with my massive mods list or specifically DimDoors 1.19.4 since it _is_ in beta, but it appears dying AT ALL, including in the overworld, sends you to limbo

### Mod Version

5.2.0

### Log

```shell
I don't exactly know what to put here, as it seems that being sent to limbo doesn't tell you what dimension you were sent from. The best i've got is this.

[01Oct2023 19:09:36.136] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ZipZipZipZipZip was slain by Pillager and was sent to Limbo
[01Oct2023 19:09:36.815] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [CHAT] ZipZipZipZipZip was slain by Pillager and was sent to Limbo
```

**Comment by Waterpicker** [comment]
Looking into it. I have a theory what's going on.

**Comment by Waterpicker** [comment]
So good news and bad news. Good news it isn't a bug. I added the ability to define a list of worlds that can send you to limbo that aren't pockets and the option have it act like a black or white list. I think I left it set by accident to be a black list by default.

**Comment by Waterpicker** [comment]
Eh the bad news is I left it as a blackList so only world listed are excluded.

**Comment by Waterpicker** [comment]
Fixed in https://github.com/DimensionalDevelopment/DimDoors/commit/c1facf263c0e7e5245ed01e74c093934658015ce
