### ISSUE TITLE
[Bug]: Lost Connection on Server Join 1.20.1

### ISSUE THREAD

**Issue by Devilswarchild** [DimensionalDevelopment/DimDoors#370]
### What happened?

![image](https://github.com/DimensionalDevelopment/DimDoors/assets/27385258/23af5058-6c99-4bf1-b7c0-d7cf42a7dbd3)

This is the error Im getting when I try to join my own server with DimensionsalDoors installed.
 works fine in singleplayer.

Minecraft: 1.20.1

[debug.log](https://github.com/DimensionalDevelopment/DimDoors/files/13382850/debug.log)
[latest.log](https://github.com/DimensionalDevelopment/DimDoors/files/13382851/latest.log)
[launcher_log.txt](https://github.com/DimensionalDevelopment/DimDoors/files/13382853/launcher_log.txt)

was unable to get them to save using mclo.gs for easier reading

### Mod Version

5.3.0-forge-beta1

**Comment by Devilswarchild** [comment]
also these are the server logs:

[debug.log](https://github.com/DimensionalDevelopment/DimDoors/files/13382864/debug.log)
[latest.log](https://github.com/DimensionalDevelopment/DimDoors/files/13382865/latest.log)

**Comment by Kangy1103** [comment]
Glad I'm not the only one! Thought I was going crazy when diagnosing this

#368

**Comment by Waterpicker** [comment]
Which beta?

**Comment by Devilswarchild** [comment]
> Which beta?

![image](https://github.com/DimensionalDevelopment/DimDoors/assets/27385258/ad81eca1-a349-476e-b7f6-3405dc62b412)

**Comment by Kangy1103** [comment]
> Which beta?

Beta 1 for me as well

**Comment by Waterpicker** [comment]
I released Beta 2 a couple days ago that fixes this issue.

**Comment by Kangy1103** [comment]
> I released Beta 2 a couple days ago that fixes this issue.

Oh perfect, thanks! Been really wanting to include this in my pack

**Comment by Devilswarchild** [comment]
just waiting on it to pop up in the app

**Comment by Devilswarchild** [comment]
it works without issue
