### ISSUE TITLE
[Bug]: Rift stabilizer recipe issue [empty item tag c:diamond]

### ISSUE THREAD

**Issue by DevDyna** [DimensionalDevelopment/DimDoors#374]
### What happened?

![image](https://github.com/DimensionalDevelopment/DimDoors/assets/78147916/1544fc38-3469-4ed9-9dc0-5a0abe13e4eb)

### Mod Version

5.3.0 beta Forge 1.20.1

**Comment by Waterpicker** [comment]
Fixed in later versions.
