### ISSUE TITLE
[Bug]: Fractal's (i think thats what they're called?) not rendering when using Rubidium on Forge 1.20.1

### ISSUE THREAD

**Issue by Kat-09** [DimensionalDevelopment/DimDoors#385]
### What happened?

Fractals are not rendering when using Rubidium (When i remove rubidium from my modpack, they render as expected)

I am using:
DimensionalDoors 5.3.1 
NeoForge 47.1.85 
Minecraft 1.20.1

### Mod Version

5.3.1

### Log

```shell
Log is at:

https://mclo.gs/BxVppIf
```

**Comment by Camawama** [comment]
I use Embedium and they render just fine. You should try using Embedium!

**Comment by Kat-09** [comment]
Thx, i'll try that!
