### ISSUE TITLE
Remove the schematic conversion code

### ISSUE THREAD

**Issue by Runemoro** [DimensionalDevelopment/DimDoors#39]
The schematic converter is currently causing several problems:
 - Incompatibility with several mods (FoamFix, EnchantingTable)
 - Won't work in 1.13 so we need to remove it by then
 - Slows down mod startup (we will eventually want to load schematics on place to solve the memory usage problem)
 - Increases the jar file size (the old numerical block id based system was much less efficient)

To remove it, we will need to:

- [x] Make sure everything is being converted properly.
- [x] Convert any other 1.6.4 dungeons that might exist somewhere else
- [x] Have a system for "default doors" to allow us to easily make changes to door properties without having to modify all schematics
- [ ] Make a tool that can open and generate schematic info, or modify all schematics in a similar way, in case we need to update block IDs/add author info to them
- [x] Convert the schematics and ~~remove the schematic converter code~~

**Comment by Robijnvogel** [comment]
"It'd be better to move this functionality out of the mod and into a separate repo."
~ @Runemoro @ZombieHDGaming and I - 2018-01-25

**Comment by Runemoro** [comment]
Done.

**Comment by Robijnvogel** [comment]
Should you really have closed this? You still have one unchecked box.
