### ISSUE TITLE
[Bug]: Teleport failing

### ISSUE THREAD

**Issue by PolyframeX** [DimensionalDevelopment/DimDoors#398]
### What happened?

When attempting to teleport through a door, an error is thrown. This may be an incompatibility with supplementaries.

### Mod Version

5.3.3

### Log

```shell
https://pastebin.com/tLtL7AXW
```

**Comment by Waterpicker** [comment]
It seems is not an an incompatibility with supplementaries. More dimensional doors encountered an edge case that wasn't account ed for.
