### ISSUE TITLE
[Suggestion]: Make pocket dungeons less far apart, or make larger pocket dungeons

### ISSUE THREAD

**Issue by akirapink** [DimensionalDevelopment/DimDoors#399]
### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion

### Use the editor below to elaborate.

Even though these aren't really meant to be lived in, current size of 32x32 chunks for each 1 segment of pocket dungeon seems really inefficient. I propose the grid size be made smaller or bigger dungeon segments be added (at the risk of making average pocket dungeon trip duration extremely long)

**Comment by Yobrocharlie** [comment]
Dude

**Comment by Yobrocharlie** [comment]
![image](https://github.com/DimensionalDevelopment/DimDoors/assets/126765898/d3def2a2-5ccb-4ac9-a6c0-4d9add46959a)

**Comment by Yobrocharlie** [comment]
Last time when I said wyci that means
When
You
Code
It,

Dimdoors doesnt need more idea guys we need developers, unless you yourself want to make these PR’s (Pull Requests) I highly suggest you just make it yourself to which it will probably get merged if it works properly.

**Comment by Yobrocharlie** [comment]
Sure suggesting a good gameplay idea can be helpful-

If there are devs who are there to enact this idea which fun fact there are not, most devs who were working on this project have their hands tied elsewhere.
