### ISSUE TITLE
[Suggestion]: Add more and improve existing dungeon segments, possibly configurable

### ISSUE THREAD

**Issue by akirapink** [DimensionalDevelopment/DimDoors#400]
### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion

### Use the editor below to elaborate.

The mod is great, I'm glad it's been ported to modern versions, but I feel as though after only 45 minutes of just exploring pocket dungeons, I've seen most of the content, which itself feels kind of basic
Suggestion: add more dungeon segments and revamp existing ones
Furthermore, possibly make dungeon segments data-driven, configurable with datapacks?

**Comment by Yobrocharlie** [comment]
Dawg

**Comment by Yobrocharlie** [comment]
Wyci

**Comment by Waterpicker** [comment]
Quick question. Are you using any dimdoors version from the middle of 1.17 current because the dungeons have been 100% data driven for years at this point.

**Comment by akirapink** [comment]
sorry
