### ISSUE TITLE
[Bug]: CurseForge is installing 5.3.0-forge-Beta1

### ISSUE THREAD

**Issue by ccfries** [DimensionalDevelopment/DimDoors#407]
### What happened?

On curseforge, "5.3.0-forge-beta1" is still the version that gets installed if you click the "Install" button, and some poor sucker (me) spends an hour trying to figure out what is wrong with his minecraft server :) 

This version has Bug #370 still exposed. 

### Mod Version

5.3.0-forge-beta1

**Comment by Waterpicker** [comment]
This bug should be fixed in later versions.
