### ISSUE TITLE
[Forge 1.20.1] [Bug]: Rift Stabilizer recipes using invalid tag

### ISSUE THREAD

**Issue by vizthex123** [DimensionalDevelopment/DimDoors#409]
### What happened?

The recipes want the `c:diamond` tag, but that doesn't exist in Forge. Should be `forge:gems/diamond` instead.

_(Also, there's no option for 1.20 in the drop-down on the issue form)_

### Mod Version

5.3.0

### What versions of Minecraft does this issue happen on?

1.19.3

**Comment by Waterpicker** [comment]
This has been fixed in later versions. Busy ironing out kinks for 5.3.4. I recommend updating to that when I do release it.
