### ISSUE TITLE
Going through rifts or Dimensional Doors crashes the game & spawned rifts have no location.

### ISSUE THREAD

**Issue by ScytheIronclaw** [DimensionalDevelopment/DimDoors#41]
Mod Version: Dimdoors-3.0.6-b.224

Going through any open Rift or any linked Warp Door or placed Dimensional Door causes the game to crash. After re-loading the world, the world becomes corrupted and gets stuck in an infinite loop after loading.

Also, generated rift clusters have no destination when placing a Warp Door on them or attempting to open them with the Rift Sword.

[crash-2018-01-26_16.03.47-server.txt](https://github.com/DimensionalDevelopment/DimDoors/files/1669237/crash-2018-01-26_16.03.47-server.txt)

**Comment by Runemoro** [comment]
Could you paste a full log? There should be an exception in TeleportUtils.<clinit>.

**Comment by ScytheIronclaw** [comment]
If by full log you mean the latest.log located in <modinstance>/logs then here you go.
[latest.log](https://github.com/DimensionalDevelopment/DimDoors/files/1669247/latest.log)

**Comment by Runemoro** [comment]
There will be a build in around 2 minutes that will fix it. Closing this rather than fixed in dev because the problem appeared since the last beta.

**Comment by ScytheIronclaw** [comment]
Awesome! Thanks for the fast response!
