### ISSUE TITLE
Audio engine crashing

### ISSUE THREAD

**Issue by Imphinium** [DimensionalDevelopment/DimDoors#45]
I've noted that when I have this mod enabled it the modpack PixelClash, there is lag every few seconds. Both graphics and server ticks in single player gets slowed down for around 20 seconds, while (using F3+Shift) I can see the audio engine resource usage going crazy, and getting lower when the problem stops. The cycle repeats itself when the resource usage of the sound engine is in it lower point.

**Comment by ZombieHDGaming** [comment]
Do you have a log for us to look at?

**Comment by Runemoro** [comment]
Could you try to find which mod in the modpack is incompatible with DimDoors?

**Comment by Runemoro** [comment]
Can't reproduce using PixelClash and Dimensional Doors 3.0.8. There's no lag and "sound" is very low in Shift+F3.
