### ISSUE TITLE
[Suggestion]: Add a tag to identity dimensional doors

### ISSUE THREAD

**Issue by RubyCascade** [DimensionalDevelopment/DimDoors#450]
### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion

### Use the editor below to elaborate.

I find it likely that you are aware of the issues caused by moving a dimensional door due to how the doors behave on Create contraptions, however Valkyrian Skies: Eureka ships can assimilate the dimensional doors thus allowing them to be moved.

There are three possible solutions (on your end) that I can think of:
1. Automatically add all dimensional doors to Valkyrien Skies: Eureka's Block Blacklist
2. Add a tag for dimensional doors _(Valkyrien Skies: Eureka's Block Blacklist doesn't currently support tags afaik, but I am making a parallel suggestion in the ValkyrienSkies/Eureka repo)_
3. Somehow prevent dimensional doors from being on Valkyrian Skies physics objects some other way

Additional info:
- Minecraft version: 1.20.1
- Mod loader: Fabric
- Loader version: 0.16.9
- Dimensional Doors version: dimdoors-5.4.1-fabric
- Valkyrian Skys version: valkyrienskies-120-2.3.0-beta.5
- Eureka version: eureka-1201-1.5.1-beta.3

(Apologies If I've made this Issue suboptimally lol, first time submitting one)

**Comment by RubyCascade** [comment]
Parallel suggestion in ValkyrienSkies/Eureka: https://github.com/ValkyrienSkies/Eureka/issues/422

**Comment by RubyCascade** [comment]
It seems like tags will be the best option.
https://github.com/ValkyrienSkies/Eureka/issues/422#issuecomment-2484690034
https://github.com/ValkyrienSkies/Eureka/issues/422#issuecomment-2484735472

**Comment by Waterpicker** [comment]
Closing as this has been completed as of https://github.com/DimensionalDevelopment/DimDoors/commit/237a1e1c4295b1326ec8b26bb27e9c3051bc0d68
