### ISSUE TITLE
[1.12.2] Crash on Startup for Server (SpongeForge)

### ISSUE THREAD

**Issue by QAngelusQ** [DimensionalDevelopment/DimDoors#46]
https://pastebin.com/cCbPprus

I get this crash report when I start up (server-side) with the latest release "Dimdoors-3.0.7-b-1.240"

**Comment by Runemoro** [comment]
Fixed, a new build (242) should be there in a few minutes solving the problem.

**Comment by Runemoro** [comment]
https://github.com/DimensionalDevelopment/DimDoors/releases/tag/untagged-b348b88004e9ed01e463
