### ISSUE TITLE
[1.12.2] Client Error message when joining server (SpongeForge)

### ISSUE THREAD

**Issue by QAngelusQ** [DimensionalDevelopment/DimDoors#47]
I recently posted an issue regarding a problem solved by the recent 242 build

After putting the 243 build into the server, when joining as the client 

I get an error message
"Fatally missing registry entries"

**Comment by Runemoro** [comment]
Can you try recreating a new world? We recently made some breaking changes in the last few dev builds (and we will still be making some in the next few builds), if you want to avoid losing pockets/doors/items/blocks, you should use the latest beta. 

I think you have to run a command on sponge to make it start the server even though it's missing block IDs, check the server console. If you do run that command, then it means you'll lose some dimdoors blocks in your world though, so make a backup first.

**Comment by QAngelusQ** [comment]
apologies i should of been more specific

i've created a new world and i still get the same error (server isn't live yet, still in development)

**Comment by Robijnvogel** [comment]
@QAngelusQ do you have the same version of the mod installed on the server AND the client?

**Comment by QAngelusQ** [comment]
Yes I have the same version on both Server and Client.
Also deleted and refreshed the configuration files.

I suspect this has something to do with [Not Enough IDs](https://minecraft.curseforge.com/projects/notenoughids) and how it registers the blocks / items with dimensional doors 2. However I am unsure where to go from here.

**Comment by Runemoro** [comment]
Does it still happen if you disable all mods except Sponge and DimDoors? If not, then try only DimDoors, Sponge and Not Enough IDs. Also, could you upload a log of your server starting up?

**Comment by QAngelusQ** [comment]
This doesn't happen if I remove all the mods and only use SpongeForge, DimDoors & NotEnoughIDs

I assume this is okay because Not Enough ID only triggers when the id limit of 4096 is exceeded

This is the log of the server startup with all the mods and getting the "Fatally Missing Registry Entries"
[latest.log](https://github.com/DimensionalDevelopment/DimDoors/files/1862743/latest.log)

**Comment by ZombieHDGaming** [comment]
As to comment on your earlier hypothesis, I think it also has something to do with NEI and what it does. I believe I've seen somewhere on another mod repo issue tracker also having this same issue. My suggestion is to maybe remove it and see if it works without it, as long as it isn't needed. I think I've also had this issue and it fixed itself after removing NEI, so I'd give it a try.

**Comment by QAngelusQ** [comment]
Unfortunately I have too many mods already that removing NEI would be impossible. Thanks for the suggestion though. Ultimately if there isn't a fix its no big deal really.

**Comment by Robijnvogel** [comment]
@QAngelusQ please understand that we are trying to find the cause of the issue here. The culprit may not even be NEI. So please at least try. I think it is in our mutual interest. :)

I also don't believe that you understand how little NEI does nowadays. It's merely a JEI addon and JEI contains most of the functionality that NEI used to. ;)

**Comment by QAngelusQ** [comment]
Wait NEI as in [Not Enough IDs](https://minecraft.curseforge.com/projects/notenoughids)
JEI has this functionality? Well A while back I tried to remove Not Enough IDs but ended up with the "exceed 4096 ids" crash error. Removed 25 or so mods just to see how far I have to go and still ended up with the error (mods removed being ones that primarily lots of blocks and items specifically). 

(Apologies if I sounded passive aggressive in my last post, I simply wouldn't want to waste your immediate time on something that might only be affecting me xD)

**Comment by ZombieHDGaming** [comment]
Hmm, I actually went back and looked at your original log and I think while NEID is affecting the mod (which we knew), I think it's also affecting Sponge based on what I saw. I know you need the mod, but as a word to the wise from LexManos himself, I'd try to stay away from NEID. It's a terribly written coremod that is in no way proper for what it should be. If anything, report this to NEID and see what they say, they are the issue here.

**Comment by QAngelusQ** [comment]
Alright will do, appreciate all the time and effort <3

**Comment by Runemoro** [comment]
@QAngelusQ Do you have less than 4096 IDs without DimDoors? In that case it might not even be DimDoors that's incompatible with Not Enough IDs, but it just happened to be the mod that got the ID count over 4096. If yes, then try replacing DimDoors with another mod that adds many blocks, and see if it still happens.

**Comment by QAngelusQ** [comment]
I have more than 4096 ids without DimDoors xD

If i remove Not Enough IDs (without DimDoors) from my pack, ill get a error message when loading (client or server) stating "java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded."

But just to make sure I just temporarily added the [Techreborn](https://minecraft.curseforge.com/projects/techreborn) mod to my pack (since it was at one time the continuation of IC2 with just as many items and blocks) to see if that was the issue. Joined the server with no issues xD. Thanks for the update though.

**Comment by Robijnvogel** [comment]
@QAngelusQ I've been playing DireWolf20's modpack for 1.12.2 lately, and I don't know what they did, but [no modded blocks or items are registered below ID 4096](https://i.imgur.com/qKcKFrO.png).
Not Enough IDs is not in the modpack, by the way.

**Comment by QAngelusQ** [comment]
perhaps the block IDs above 4096 are valid because the grand total of block ids being used is <= 4096 ?
Not sure, very interesting though.
