### ISSUE TITLE
Failed to teleport

### ISSUE THREAD

**Issue by theishiopian** [DimensionalDevelopment/DimDoors#51]
When you walk into a door, it says the teleport failed and asks you to report the bug. Seems to affect any door that was newly placed, but not doors created from pre-existing rifts. 

Log:
[https://pastebin.com/HmZNi4S4](url)

I'm using Forge 14.23.3.2668, and no other mods

**Comment by Runemoro** [comment]
Thanks for reporting this so quickly. The newest release, as well as the CurseForge jar, will fix this.

**Comment by theishiopian** [comment]
No problem, I know from experience that null pointer exceptions are a pain in the ass.

**Comment by jepo** [comment]
This still happens on the latest version (B8 271).

Creating a personal pocket dimension with a quartz door, every time the door is entered you are taken to a fresh dimension. This can eventually cause a crash.

[18:24:36] [main/INFO]: [CHAT] Something went wrong while trying to teleport you, please report this bug.
https://pastebin.com/4PYDpVWx

**Comment by Runemoro** [comment]
@jepo That is a different but unrelated to this one. Use the following release instead: https://github.com/DimensionalDevelopment/DimDoors/releases/tag/untagged-f66fe1d7a82c474b8644
