### ISSUE TITLE
Incompatibility with Lapis Stays in the Enchanting Table

### ISSUE THREAD

**Issue by Dalethium** [DimensionalDevelopment/DimDoors#52]
Hey! So I am so excited to see someone working on this mod for newer versions of minecraft, however it has a server startup crash with the mod by crazysnailboy. [Crash Report](https://pastebin.com/fPsmh9gg)

I've reported this issue to their repo [here](https://github.com/crazysnailboy/EnchantingTable/issues/10) too!

Thanks! Good luck!

**Comment by Sunconure11** [comment]
I can confirm this issue. It's the same issue as it's incompatibility with Exotic Birds.

https://pastebin.com/gasFhvpZ

https://github.com/crazysnailboy/EnchantingTable/issues/8

**Comment by Robijnvogel** [comment]
This looks like a combination of their ASM and our unexpectedly early usage of some of MC's functionality.

I wonder what safeguards we can build in: https://github.com/crazysnailboy/EnchantingTable/issues/6

**Comment by Runemoro** [comment]
We sent a pull request to EnchantingTable: https://github.com/crazysnailboy/EnchantingTable/pull/11. Until then, you can use this custom build of EnchantingTable: https://github.com/DimensionalDevelopment/EnchantingTable/releases/download/capabilities-fix/EnchantingTable-1.12-1.1.2-CapabilitiesFix.jar

**Comment by Sunconure11** [comment]
Could you create a curse page, called Lapis Stays in The Enchanting Table Unofficial, until the dev returns, @Runemoro? Just so those who want to use it in a curse pack don't have to deal with curse rejecting their packs for using it.

**Comment by Dalethium** [comment]
Thanks very much! I truly appreciate you taking the time @Runemoro ! I'll test the build out later today to see if it works!
