### ISSUE TITLE
Client crash with limbo & the eternal fabric

### ISSUE THREAD

**Issue by Dalethium** [DimensionalDevelopment/DimDoors#54]
[Crash log](https://pastebin.com/rLQ0z2dz)

I tried to mine the red and white fabric (what I assume was eternal) and my client crashed, the server logged no errors. I was flying so I am not sure if my player touched the block itself.

I am not sure if this is a duplicate of #18 or not, sorry if it is.

If you need anything else just let me know!

PS: Thanks so much for reviving this classic, it's much appreciated.

**Comment by Dalethium** [comment]
Just double checked, it happens when I touch the fabric (like walk on it)

**Comment by Andromander** [comment]
Might it have something to do with Galacticraft? I can see references to it in the stacktrace.

**Comment by Robijnvogel** [comment]
@Andromander probably not.

**Comment by Runemoro** [comment]
Could you check if this build fixes it? https://github.com/DimensionalDevelopment/DimDoors/releases/download/untagged-0c50e29916cc1be445ad/DimensionalDoors-3.0.8-273.jar

**Comment by Dalethium** [comment]
Sure! I'll check later today! Thanks for the speedy fix!

**Comment by Dalethium** [comment]
Just tested it! Wound up in the overworld as intended! Thanks so much!
