### ISSUE TITLE
Particle decay issue

### ISSUE THREAD

**Issue by theishiopian** [DimensionalDevelopment/DimDoors#55]
![2018-04-18_21 14 00](https://user-images.githubusercontent.com/8585975/38971002-a6b24b04-434d-11e8-86d4-c927f058d106.png)

These particles are just hanging in the air, not disappearing. They are still animating, but are not moving. 

How to reproduce:

1. pass through a naturally generated gateway into a dimensional dungeon.

2. exit the dungeon. the gateway is now a rift.

3. place an iron dimensional door on the rift

Reloading the world makes the particles go away.

Graphics mods present: optifine HD_U_D1, better fps 1.4.8, no potion glint 1.0.0

**Comment by theishiopian** [comment]
Update:

Issue persists even when no graphics mods are present (I am using cubic chunks though, forgot to mention that last post). Additionally, the issue also affects rifts without doors.

**Comment by Runemoro** [comment]
The particles should slowly disappear. Are you sure they don't? They can take up to a few minutes to fully disappear?

**Comment by theishiopian** [comment]
I watched for quite some time. I can watch for longer, but I don't think they decay.

**Comment by theishiopian** [comment]
After watching for a few minutes, I can confirm that they do decay eventually. It still seems a little long though.

**Comment by Runemoro** [comment]
Yes, that's what's intended. The particles represent void particles that escaped from the other side of the rift, not just any regular minecraft particle.

**Comment by theishiopian** [comment]
Fascinating. Perhaps there should be some use for this. Surely void particles must have at least some practical applications.
