### ISSUE TITLE
Incompatibility with PerfectSpawn

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [DimensionalDevelopment/DimDoors#58]
[crash-2018-04-19_11.54.39-server.txt](https://github.com/DimensionalDevelopment/DimDoors/files/1927706/crash-2018-04-19_11.54.39-server.txt)

**Comment by Runemoro** [comment]
Could you report this to PerfectSpawn too? They seem to be doing something wrong while trying to get the spawnpoint.

**Comment by Runemoro** [comment]
Fixed in next dev build.
