### ISSUE TITLE
If cubic chunks is installed, teleportation fails if the world isn't a cubic chunks world.

### ISSUE THREAD

**Issue by theishiopian** [DimensionalDevelopment/DimDoors#59]
https://pastebin.com/Lbd5hbJ8

**Comment by theishiopian** [comment]
Unfortunately the pastebin link wouldn't work, sorry for the wall of text.

**Comment by Runemoro** [comment]
The pastebin link probably didn't work because you used the Github link button. That turns text into a link, and asks you to give it a URL: `[text](url)`, so it won't work unless you change url. For a regular link (text same as url), just paste the link without doing anything.

**Comment by theishiopian** [comment]
Ah, ok, Let me fix it real quick

**Comment by theishiopian** [comment]
Much better

**Comment by Runemoro** [comment]
Fixed in next dev build.

**Comment by theishiopian** [comment]
Can I just say I really appreciate all the work you guys put into mod compat?
