### ISSUE TITLE
Teleporting into walls when going to Dungeon Pockets

### ISSUE THREAD

**Issue by Robijnvogel** [DimensionalDevelopment/DimDoors#6]
- [x] DimDoors' Tile Entities seem to have incorrect orientation data, causing them to tell the "Teleporter" to teleport players to the left side of the door instead of the front.
- [ ] While fixing this, changing the player's view direction to "away from the door" might be implemented as well.

**Comment by Robijnvogel** [comment]
https://github.com/DimensionalDevelopment/DimDoors/blob/1.10-WIP/src/main/java/com/zixiken/dimdoors/shared/DDProxyCommon.java#L60 
seems to have to do with this.

**Comment by Runemoro** [comment]
Fixed. Dimensional doors now always teleport you one block in front of the door.
