### ISSUE TITLE
Dungeon gateways don't seem to generate in other world types.

### ISSUE THREAD

**Issue by theishiopian** [DimensionalDevelopment/DimDoors#60]
Admittedly, this needs further testing, but I couldn't find any dungeon gates in a customcubic world. I'll try testing with non vanilla, non cubic chunks worlds next.

**Comment by Runemoro** [comment]
Are you sure they don't? Try increasing the frequency in the config. In any case, the generator we're using works for all world types (it was tested with Biomes O' Plenty), so that would be a CubicChunks bug.

**Comment by theishiopian** [comment]
Huh, I guess I'll open an issue there then.

**Comment by Runemoro** [comment]
Gateways are very rare though, by default it's 1/10000 chunks. You can make them spawn more often by changing the mod options.

**Comment by theishiopian** [comment]
I'll try that

**Comment by theishiopian** [comment]
Definitely a cubic chunks issue, set the gen chance to 1, nothing.

**Comment by theishiopian** [comment]
According to Barteks, other mods stuff wont generate in customcubic on purpose. Apparently its not reliable enough yet. Mystery solved.
