### ISSUE TITLE
Gateways stop rendering if you get to close to them.

### ISSUE THREAD

**Issue by theishiopian** [DimensionalDevelopment/DimDoors#61]
Happens both with and without optifine. Unfortunately, I was unable to record a gif, but the title should be pretty self explanatory.  The gateway simply disappears. It reappears if you step back.

**Comment by Runemoro** [comment]
Could you post an image? It's working fine for me...
![2018-04-20_01 11 36](https://user-images.githubusercontent.com/2412762/39031710-d92392f6-4437-11e8-8354-e3b15b55a6d4.png)

**Comment by theishiopian** [comment]
Theres no glitch, it just vanishes. I'll try to record a gif if I encounter it again. Its probably connected to the age old bug in minecraft where tile entities stop rendering at the edge of your vision. Which, by the way, affects rift renders as well.

**Comment by Runemoro** [comment]
Fixed in next dev build.
