### ISSUE TITLE
Global warming?

### ISSUE THREAD

**Issue by theishiopian** [DimensionalDevelopment/DimDoors#62]
Not really sure what to make of this. Whenever I exit a dimensional dungeon, I get set on fire. Additionally, the world seems to be catching fire gradually. Did I release a Cthuga or something? 
![2018-04-21_10 20 08](https://user-images.githubusercontent.com/8585975/39086954-d3d7811a-454d-11e8-97aa-8cad7099056c.png)

**Comment by Robijnvogel** [comment]
The first thing is caused by a Vanilla bug that rarely occurs in Vanilla itself.
I can't quite explain the second one. Is it not lightning?

**Comment by Runemoro** [comment]
https://bugs.mojang.com/browse/MC-98153

**Comment by theishiopian** [comment]
No, the sky was very much clear. Also, the patches of fire are too large for lightning strikes.

**Comment by theishiopian** [comment]
![2018-04-21_14 11 24](https://user-images.githubusercontent.com/8585975/39088822-f7a0eef4-456d-11e8-9b4d-b9ddfa278c4c.png)
The fire seems to be limited to the area of loaded chunks around the dungeon gateways I've been playing with. The patches in the jungle seem smaller than the ones on the plains.

**Comment by Runemoro** [comment]
Fixed in the latest release (https://github.com/DimensionalDevelopment/DimDoors/releases/latest). It should also fix it for vanilla (nether and end portals).

**Comment by theishiopian** [comment]
Hopefully this fixes the world fire, but I somehow doubt it.

**Comment by Robijnvogel** [comment]
@Runemoro we only looked at one of the sub-issues here...

Even though I doubt that the other one has anything to do with Dimensional Doors.

**Comment by Runemoro** [comment]
The only way the world could be set on fire from DimDoors is if the rift block was somehow mapped to the fire block instead, and those were rift clusters.

@theishiopian If you set the rift cluster gen chance to its maximum (1), does the amount of fire increase? If yes, if you disable it (set it to 0), does the fire stop?

**Comment by theishiopian** [comment]
What are rift clusters? are they a byproduct of dimensional rifts? Unless they are, I dont think your suggestion is the case, as the fire wasnt there when the world first generated.

**Comment by Runemoro** [comment]
No, rift clusters are rifts randomly generating in the world, so if the wrong block was being placed for some reason, the fire would be there on worldgen.

Are you able to reproduce the bug in a new world?

**Comment by theishiopian** [comment]
Ok, so if rift clusters are generated with the world, that cant be the issue, as the fire was definitely not there when the world was first generated. 

As for reproducing it, I'll try some experiments later tonight, and report back with the results. I'll also try messing with rift cluster generation, just in case.

**Comment by Robijnvogel** [comment]
@theishiopian found anything new?

**Comment by theishiopian** [comment]
Not really no, I think its safe to close this unless it happens again.
