### ISSUE TITLE
[1.12.2] Multiplayer Random Dungeon Support

### ISSUE THREAD

**Issue by MokahTGS** [DimensionalDevelopment/DimDoors#66]
We have found a small issue with random spawning dungeon doors where they disappear when the first player goes in making it impossible for the second player to follow in a multiplayer scenario.

We tested this in a MP LAN environment but I'm assuming it does the same thing on a server.

**Comment by Robijnvogel** [comment]
The Transient Doors are intended to only let in one player before collapsing to a Rift Tear. You then need to place a Door on this Tear to stabilise it so it can be used again.

**Comment by MokahTGS** [comment]
Ah, thanks.  So the other player would end up in the same place as the first player?

**Comment by Runemoro** [comment]
Using either:
  - A dimensional door placed on the rift tear
  - An enderpearl thrown through the portal
  - A rift blade, used either on the portal or the rift tear

Just to confirm, the rift tear (large black tear in the world) is showing up, right?

**Comment by MokahTGS** [comment]
Yes.  Thanks!
