### ISSUE TITLE
[1.12.2] ticking player crash when entering ANY dimension. 

### ISSUE THREAD

**Issue by Snerfoil** [DimensionalDevelopment/DimDoors#67]
Here is the weird thing however. I attempted to replicate this crash and was unable to do so, there is only ONE save I have where this occurs and I dont know why. one thing I will say about the save is that it was in survival mode and was created before installing the mod (mind you I tried to replicate this in another save, but that time it worked fine).
link to crash info https://www.dropbox.com/s/xuyoy8gnc90p5gz/crash-2018-05-18_12.00.35-server.txt?dl=0
also a link to the log https://www.dropbox.com/s/l7go17p8ifmxf0b/latest.log?dl=0

I will try to keep looking into whats triggering this.

**Comment by Snerfoil** [comment]
oh! yeah I just went and did that, Antique Atlas is borking it. anyway thanks :3

**Comment by Kenkron** [comment]
Sorry about all the confusion, I fixed this in 4.4.9.
