### ISSUE TITLE
Return from Limbo at the bottom of the ocean

### ISSUE THREAD

**Issue by scribbler957** [DimensionalDevelopment/DimDoors#78]
I'm starting a new world, and in my old one, when I returned from limbo by death or fabric, I always appeared at the bottom of the ocean in the middle of nowhere. I had never been to that spot prior to coming back from limbo. Is it a mapping from Limbo itself?

**Comment by Robijnvogel** [comment]
At the moment, it should send you to the x and z coordinates that you escaped from Limbo from. Which are a random transformation of the x and z coordinates of the Dungeon Pocket, which in their turn are a random transformation of the x and z coordinates of the original door that you entered from in the Overworld.

It should not put you at the surface of the ocean, though, not at the bottom. If it does that, that's probably a bug.

**Comment by scribbler957** [comment]
I was at the bottom of the ocean. I know because I hadn't noticed I had left limbo at first because it was so dark down there.

**Comment by Robijnvogel** [comment]
Confirmed in dev

**Comment by Robijnvogel** [comment]
Caused by https://github.com/ModCoderPack/MCPBot-Issues/issues/392

I'll see what we can do. :)
