### ISSUE TITLE
List of dimension IDs for dimensional doors?

### ISSUE THREAD

**Issue by alxpettit** [DimensionalDevelopment/DimDoors#84]
So, the creator of the Gravestone mod just added a blacklist feature, which should improve interoperability with this mod [(before, it was stealing the inventory and then throwing it away, when they fall into the void)](https://github.com/NightKosh/Gravestone-mod-Graves/issues/272).

I'd like to go further and suggest adding a built in blacklist to make Gravestone compatible out of the box with DimensionalDoors... the only problem is, I need to know which IDs we should be blacklisted by default. So, my question is, where can I find a list of IDs for the dimensions I need to blacklist to prevent item loss, and are these IDs static and reliable?

**Comment by ZombieHDGaming** [comment]
If you look in the in-game config, there will be an option which allows you to set the starting ID for DimDoors dimensions in the general options. That number is what the dimensions are registered as in the game. It should be simply taking that number and adding it to the blacklist for the Gravestone mod and it *should* work as intended. If it doesn't work, just report back here and tell us what's up with it.

**Comment by alxpettit** [comment]
Okay, thanks! :)
