### ISSUE TITLE
"Something went wrong while trying to teleport you"

### ISSUE THREAD

**Issue by GildedLight** [DimensionalDevelopment/DimDoors#95]
I'm playing a lightly modded survival (Tinkers', and 2-3 utility mods) and just got a personal pocket dimension, with the Quartz door and all. I got in, poked around in it for a bit, left, saved and quit. when i reloaded the world, and tried to reenter the pocket dimension, none of the blocks id placed were there and i got the error: "Something went wrong while trying to teleport you, please report this bug" And upon leaving the pocket dimension I got "You didn't use a Rift to enter the pocket dimension, and ended up in limbo!" I'd seen the same bug in my creative world so i knew well enough to turn on 'KeepInventory' and as such didnt lose anything, but figured it was well worth reporting.

**Comment by Robijnvogel** [comment]
Duplicate of #85
